/**
 * Currency tables, ported 1:1 from the RN app (constants/currencies.ts).
 *
 * CURRENCY_SYMBOLS: minimal symbol lookup for the savings affix display and
 * the allow-list for the settings picker. Falls back to the raw code when a
 * symbol isn't found.
 *
 * REGION_TO_CURRENCY: region code → preferred currency for first-run
 * auto-detection (covers UN member states plus major territories).
 */

export const CURRENCY_SYMBOLS: Record<string, string> = {
  // ── Major ──
  EUR: '€',
  USD: '$',
  GBP: '£',
  JPY: '¥',
  CHF: 'Fr',
  CNY: '¥',
  // ── Dollar variants ──
  AUD: 'A$',
  CAD: 'CA$',
  HKD: 'HK$',
  NZD: 'NZ$',
  SGD: 'S$',
  TWD: 'NT$',
  MOP: 'MOP$',
  TTD: 'TT$',
  BMD: '$',
  BND: 'B$',
  BSD: '$',
  BZD: '$',
  FJD: '$',
  GYD: '$',
  KYD: '$',
  LRD: '$',
  NAD: '$',
  SRD: '$',
  SBD: 'SI$',
  XCD: 'EC$',
  // ── Peso variants ──
  ARS: '$',
  CLP: '$',
  COP: '$',
  CUP: '$',
  DOP: '$',
  MXN: '$',
  UYU: '$',
  PHP: '₱',
  // ── Real / Boliviano / Sol ──
  BRL: 'R$',
  BOB: 'Bs',
  PEN: 'S/',
  // ── Nordic krone/krona ──
  DKK: 'kr',
  NOK: 'kr',
  SEK: 'kr',
  ISK: 'kr',
  // ── Eastern Europe ──
  PLN: 'zł',
  CZK: 'Kč',
  HUF: 'Ft',
  RON: 'lei',
  BGN: 'лв',
  HRK: 'kn',
  RSD: 'дин.',
  UAH: '₴',
  RUB: '₽',
  TRY: '₺',
  GEL: '₾',
  AMD: '֏',
  AZN: '₼',
  KZT: '₸',
  // ── Middle East ──
  ILS: '₪',
  SAR: '﷼',
  AED: 'د.إ',
  QAR: 'ر.ق',
  OMR: 'ر.ع.',
  KWD: 'د.ك',
  BHD: 'د.ب',
  JOD: 'د.ا',
  IRR: '﷼',
  IQD: 'د.ع',
  LBP: 'ل.ل',
  EGP: 'E£',
  // ── South / SE Asia ──
  INR: '₹',
  PKR: '₨',
  LKR: 'Rs',
  BDT: '৳',
  NPR: 'Rs',
  MVR: 'Rf',
  MMK: 'K',
  LAK: '₭',
  KHR: '៛',
  THB: '฿',
  VND: '₫',
  IDR: 'Rp',
  MYR: 'RM',
  KRW: '₩',
  // ── Africa ──
  ZAR: 'R',
  NGN: '₦',
  GHS: '₵',
  KES: 'KSh',
  UGX: 'USh',
  TZS: 'TSh',
  MUR: '₨',
  MGA: 'Ar',
  MWK: 'MK',
  ZMW: 'ZK',
  BWP: 'P',
  LSL: 'L',
  SZL: 'E',
  XOF: 'CFA',
  XAF: 'FCFA',
  XPF: 'F',
  MAD: 'د.م.',
  TND: 'د.ت',
  DZD: 'د.ج',
  LYD: 'ل.د',
  SDG: 'ج.س',
  ETB: 'Br',
  // ── Americas ──
  CRC: '₡',
  PAB: 'B/.',
  GTQ: 'Q',
  HNL: 'L',
  NIO: 'C$',
  HTG: 'G',
  JMD: 'J$',
  BBD: 'Bds$',
  // ── Other ──
  PGK: 'K',
  WST: 'WS$',
  TOP: 'T$',
  VUV: 'VT',
  MNT: '₮',
  MKD: 'ден',
  ALL: 'L',
  BAM: 'KM',
  MDL: 'L',
  XDR: 'SDR',
}

export const REGION_TO_CURRENCY: Record<string, string> = {
  // ═══════════════════════════════════════════════════════════════════════
  //  Europe
  // ═══════════════════════════════════════════════════════════════════════
  PT: 'EUR',
  ES: 'EUR',
  FR: 'EUR',
  DE: 'EUR',
  IT: 'EUR',
  NL: 'EUR',
  BE: 'EUR',
  AT: 'EUR',
  IE: 'EUR',
  FI: 'EUR',
  GR: 'EUR',
  LU: 'EUR',
  SK: 'EUR',
  SI: 'EUR',
  EE: 'EUR',
  LT: 'EUR',
  LV: 'EUR',
  HR: 'EUR',
  MT: 'EUR',
  CY: 'EUR',
  AD: 'EUR',
  MC: 'EUR',
  SM: 'EUR',
  VA: 'EUR',
  ME: 'EUR',
  XK: 'EUR',
  GB: 'GBP',
  GI: 'GIP',
  FO: 'DKK',
  IM: 'GBP',
  JE: 'GBP',
  GG: 'GBP',
  CH: 'CHF',
  LI: 'CHF',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  IS: 'ISK',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  BG: 'BGN',
  RS: 'RSD',
  BA: 'BAM',
  AL: 'ALL',
  MK: 'MKD',
  MD: 'MDL',
  UA: 'UAH',
  BY: 'BYN',
  RU: 'RUB',
  TR: 'TRY',
  AM: 'AMD',
  AZ: 'AZN',
  GE: 'GEL',
  // ═══════════════════════════════════════════════════════════════════════
  //  Americas
  // ═══════════════════════════════════════════════════════════════════════
  US: 'USD',
  CA: 'CAD',
  MX: 'MXN',
  BR: 'BRL',
  AR: 'ARS',
  CL: 'CLP',
  CO: 'COP',
  PE: 'PEN',
  EC: 'USD',
  BO: 'BOB',
  PY: 'PYG',
  UY: 'UYU',
  GY: 'GYD',
  SR: 'SRD',
  VE: 'VES',
  CR: 'CRC',
  SV: 'USD',
  GT: 'GTQ',
  HN: 'HNL',
  NI: 'NIO',
  PA: 'PAB',
  DO: 'DOP',
  CU: 'CUP',
  HT: 'HTG',
  JM: 'JMD',
  BB: 'BBD',
  BS: 'BSD',
  BZ: 'BZD',
  TT: 'TTD',
  AG: 'XCD',
  DM: 'XCD',
  GD: 'XCD',
  KN: 'XCD',
  LC: 'XCD',
  VC: 'XCD',
  // ═══════════════════════════════════════════════════════════════════════
  //  Asia & Pacific
  // ═══════════════════════════════════════════════════════════════════════
  JP: 'JPY',
  CN: 'CNY',
  IN: 'INR',
  KR: 'KRW',
  AU: 'AUD',
  NZ: 'NZD',
  HK: 'HKD',
  TW: 'TWD',
  MO: 'MOP',
  SG: 'SGD',
  MY: 'MYR',
  TH: 'THB',
  ID: 'IDR',
  PH: 'PHP',
  VN: 'VND',
  BN: 'BND',
  KH: 'KHR',
  LA: 'LAK',
  MM: 'MMK',
  MV: 'MVR',
  LK: 'LKR',
  BD: 'BDT',
  NP: 'NPR',
  PK: 'PKR',
  AF: 'AFN',
  BT: 'BTN',
  TL: 'USD',
  PG: 'PGK',
  FJ: 'FJD',
  SB: 'SBD',
  VU: 'VUV',
  WS: 'WST',
  TO: 'TOP',
  TV: 'AUD',
  KI: 'AUD',
  FM: 'USD',
  MH: 'USD',
  PW: 'USD',
  // ═══════════════════════════════════════════════════════════════════════
  //  Middle East
  // ═══════════════════════════════════════════════════════════════════════
  IL: 'ILS',
  AE: 'AED',
  SA: 'SAR',
  QA: 'QAR',
  OM: 'OMR',
  KW: 'KWD',
  BH: 'BHD',
  JO: 'JOD',
  IQ: 'IQD',
  LB: 'LBP',
  YE: 'YER',
  IR: 'IRR',
  SY: 'SYP',
  // ═══════════════════════════════════════════════════════════════════════
  //  Africa
  // ═══════════════════════════════════════════════════════════════════════
  ZA: 'ZAR',
  NG: 'NGN',
  EG: 'EGP',
  MA: 'MAD',
  DZ: 'DZD',
  TN: 'TND',
  LY: 'LYD',
  SD: 'SDG',
  SS: 'SSP',
  KE: 'KES',
  UG: 'UGX',
  TZ: 'TZS',
  GH: 'GHS',
  ET: 'ETB',
  CM: 'XAF',
  CF: 'XAF',
  TD: 'XAF',
  CG: 'XAF',
  GA: 'XAF',
  GQ: 'XAF',
  BJ: 'XOF',
  BF: 'XOF',
  CI: 'XOF',
  GW: 'XOF',
  ML: 'XOF',
  NE: 'XOF',
  SN: 'XOF',
  TG: 'XOF',
  AO: 'AOA',
  BW: 'BWP',
  BI: 'BIF',
  CV: 'CVE',
  KM: 'KMF',
  CD: 'CDF',
  DJ: 'DJF',
  ER: 'ERN',
  GM: 'GMD',
  GN: 'GNF',
  LS: 'LSL',
  LR: 'LRD',
  MG: 'MGA',
  MW: 'MWK',
  MR: 'MRU',
  MU: 'MUR',
  MZ: 'MZN',
  NA: 'NAD',
  RW: 'RWF',
  ST: 'STN',
  SL: 'SLL',
  SO: 'SOS',
  SZ: 'SZL',
  ZM: 'ZMW',
  ZW: 'ZWL',
  // ═══════════════════════════════════════════════════════════════════════
  //  Other / Territories
  // ═══════════════════════════════════════════════════════════════════════
  PR: 'USD',
  GU: 'USD',
  VI: 'USD',
  AS: 'USD',
  MP: 'USD',
  TC: 'USD',
  KY: 'KYD',
  BM: 'BMD',
  AW: 'AWG',
  CW: 'ANG',
  SX: 'ANG',
  BQ: 'USD',
  PF: 'XPF',
  NC: 'XPF',
  WF: 'XPF',
  RE: 'EUR',
  YT: 'EUR',
  GF: 'EUR',
  GP: 'EUR',
  MQ: 'EUR',
  PM: 'EUR',
  BL: 'EUR',
  MF: 'EUR',
  SH: 'SHP',
  CK: 'NZD',
  NU: 'NZD',
  FK: 'FKP',
}

// ---------------------------------------------------------------------------
// Settings picker list
// ---------------------------------------------------------------------------

export interface CurrencyOption {
  code: string
  symbol: string
  /** Localized currency name via Intl.DisplayNames (e.g. "Euro"). */
  name: string
}

/**
 * Currency options for the settings picker: the runtime's supported
 * currencies (`Intl.supportedValuesOf`) restricted to the CURRENCY_SYMBOLS
 * allow-list, sorted by the localized name. Falls back to the map keys when
 * `Intl.supportedValuesOf` is unavailable.
 */
export const getCurrencyList = (locale: string): CurrencyOption[] => {
  const codes
    = typeof Intl.supportedValuesOf === 'function'
      ? Intl.supportedValuesOf('currency').filter(
          code => code in CURRENCY_SYMBOLS,
        )
      : Object.keys(CURRENCY_SYMBOLS)

  let names: Intl.DisplayNames
  try {
    names = new Intl.DisplayNames([locale, 'en'], { type: 'currency' })
  }
  catch {
    names = new Intl.DisplayNames('en', { type: 'currency' })
  }

  return codes
    .map(code => ({
      code,
      symbol: CURRENCY_SYMBOLS[code] ?? code,
      name: names.of(code) ?? code,
    }))
    .sort((a, b) => a.name.localeCompare(b.name, locale))
}
